export const IS_AUTH = 'IS_AUTH'
export const SETUP = 'SETUP'
export const NEEDS_AUTH = 'NEEDS_AUTH'
export const LOADING = 'LOADING'
export const CHECK_AUTH = 'CHECK_AUTH'
export const VERIFY_EXISTING_USER = 'VERIFY_EXISTING_USER'
export const ONLINE = 'ONLINE'
export const OFFLINE = 'OFFLINE'
export const LOGOUT = 'LOGOUT'
export const TOKEN = 'TOKEN'
export const STATUS = 'STATUS'
export const WORK_WITH_CACHE = 'WORK_WITH_CACHE'
export const WORK_WITH_SERVER = 'WORK_WITH_SERVER'
export const HOME_READY = 'HOME_READY'
export const SKIP_SETUP = 'SKIP_SETUP'
export const BATTERY = 'BATTERY'

